spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:h2:file:./test
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimumIdle: 2
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
      pool-name:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      jdbc:
        lob:
          non_contextual_creation: true

  sql:
    init:
      mode: always
#      mode: embedded

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: consulta-creditos-topic

#  h2:
#    console:
#      enabled: true
#      path: /h2-database

springdoc:
  swagger-ui:
    url: "/v3/api-docs"
    configUrl: "/v3/api-docs/swagger-config"
    operationsSorter: alpha
    tagsSorter: alpha

server:
  port: 8080
  forward-headers-strategy: framework
  error:
    include-exception: false